<?php

namespace AppBundle\Repository;

/**
 * LocacalidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocacalidadRepository extends \Doctrine\ORM\EntityRepository
{
}
