<?php

namespace AppBundle\Repository;

/**
 * PerfilUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerfilUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
