<?php

namespace AppBundle\Repository;

/**
 * PerfilEmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PerfilEmpresaRepository extends \Doctrine\ORM\EntityRepository
{
}
